name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 18
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run Playwright tests
      run: npx playwright test --update-snapshots
      env:
        BASE_URL: ${{ secrets.BASE_URL }}

    # NEW STEP: This saves the Linux snapshots so you can download them!
    - name: Upload Snapshots Artifact
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: linux-snapshots
        path: tests/visual.spec.ts-snapshots/
        retention-days: 1

    - name: Get Allure history
      uses: actions/checkout@v4
      if: always()
      continue-on-error: true
      with:
        ref: gh-pages
        path: gh-pages

    - name: Generate Allure Report
      uses: simple-elf/allure-report-action@master
      if: always()
      with:
        allure_results: allure-results
        allure_history: allure-history

    - name: Deploy report to Github Pages
      if: always()
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages
        publish_dir: allure-history
        commit_message: "Deploy Allure Report [skip ci]"